#Personal Fitness Tracker
#Author's Names: Eric Pan and Demili Pichay
#Last Date Modified: April 8, 2021

#Opens the file for the steps
filename=open('steps.txt','r')

#Function that takes the file of steps and days to get the average steps
def averageSteps(filename, dayCounts):
    #reads each line in the file containing steps
    steps_list=filename.readlines()
    i=0
    #loop to get rid of the line spacing
    while i<dayCounts:
        steps_list[i]=int(steps_list[i].rstrip('\n'))
        i+=1
    #assigns month to corresponding steps in the list of steps    
    january=steps_list[0:31]
    february=steps_list[31:59]
    march=steps_list[59:90]
    april=steps_list[90:120]
    may=steps_list[120:151]
    june=steps_list[151:181]
    july=steps_list[181:212]
    august=steps_list[212:243]
    september=steps_list[243:273]
    october=steps_list[273:304]
    november=steps_list[304:334]
    december=steps_list[334:365]

    month_list=[january,february,march,april,may,june,july,\
                august,september,october,november,december]
    
    averageOfMonth=[]
    highest_average=0
    lowest_average=1000000
    #loop to obtain total, highest average, and lowest average steps
    for i in range(len(month_list)):
        daysInMonth=0
        total_steps=0
        #loop to add up all the steps
        for steps in month_list[i]:
            total_steps=total_steps+steps
            daysInMonth+=1
            #The month's average is generated by dividing total steps and days in the month
        monthAve=(total_steps/daysInMonth)
        aveSteps=format(monthAve,'.1f')
        #adds the month's average to a list containing only the averages of the months
        averageOfMonth.append(aveSteps)
        #highest and lowest average steps in a month is compared with each average
        if monthAve>highest_average:
            highest_average=monthAve
            highest_average_month=i
        elif monthAve<lowest_average:
            lowest_average=monthAve
            lowest_average_month=i
    
        
    month_names=["January","February","March","April","May","June","July",\
                 "August","September","October","November","December"]
    i=0
    k=0
    #while loop to print out month's average steps for all months
    while i<len(averageOfMonth) and k<len(month_names):
            print("The average steps taken in",month_names[k],\
                  "was",averageOfMonth[i])
            i+=1
            k+=1
    else:
        print()
        
    print("The month with the highest average is",month_names[highest_average_month], \
            "and it has",format(highest_average,'.1f'), "steps")
    print("The month with the lowest average is",month_names[lowest_average_month],\
          "and it has",format(lowest_average,'.1f'), "steps")
    
         
def main():
    averageSteps(filename,365)
main()
